"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Uchazec = void 0;
var typeorm_1 = require("typeorm");
var Uchazec = function () {
    var _classDecorators = [(0, typeorm_1.Entity)()];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _rok_decorators;
    var _rok_initializers = [];
    var _rok_extraInitializers = [];
    var _kolo_decorators;
    var _kolo_initializers = [];
    var _kolo_extraInitializers = [];
    var _ss1_redizo_decorators;
    var _ss1_redizo_initializers = [];
    var _ss1_redizo_extraInitializers = [];
    var _ss2_redizo_decorators;
    var _ss2_redizo_initializers = [];
    var _ss2_redizo_extraInitializers = [];
    var _ss3_redizo_decorators;
    var _ss3_redizo_initializers = [];
    var _ss3_redizo_extraInitializers = [];
    var _ss4_redizo_decorators;
    var _ss4_redizo_initializers = [];
    var _ss4_redizo_extraInitializers = [];
    var _ss5_redizo_decorators;
    var _ss5_redizo_initializers = [];
    var _ss5_redizo_extraInitializers = [];
    var _ss1_zrizovatel_decorators;
    var _ss1_zrizovatel_initializers = [];
    var _ss1_zrizovatel_extraInitializers = [];
    var _ss2_zrizovatel_decorators;
    var _ss2_zrizovatel_initializers = [];
    var _ss2_zrizovatel_extraInitializers = [];
    var _ss3_zrizovatel_decorators;
    var _ss3_zrizovatel_initializers = [];
    var _ss3_zrizovatel_extraInitializers = [];
    var _ss4_zrizovatel_decorators;
    var _ss4_zrizovatel_initializers = [];
    var _ss4_zrizovatel_extraInitializers = [];
    var _ss5_zrizovatel_decorators;
    var _ss5_zrizovatel_initializers = [];
    var _ss5_zrizovatel_extraInitializers = [];
    var _ss1_kkov_decorators;
    var _ss1_kkov_initializers = [];
    var _ss1_kkov_extraInitializers = [];
    var _ss2_kkov_decorators;
    var _ss2_kkov_initializers = [];
    var _ss2_kkov_extraInitializers = [];
    var _ss3_kkov_decorators;
    var _ss3_kkov_initializers = [];
    var _ss3_kkov_extraInitializers = [];
    var _ss4_kkov_decorators;
    var _ss4_kkov_initializers = [];
    var _ss4_kkov_extraInitializers = [];
    var _ss5_kkov_decorators;
    var _ss5_kkov_initializers = [];
    var _ss5_kkov_extraInitializers = [];
    var _ss1_forma_decorators;
    var _ss1_forma_initializers = [];
    var _ss1_forma_extraInitializers = [];
    var _ss2_forma_decorators;
    var _ss2_forma_initializers = [];
    var _ss2_forma_extraInitializers = [];
    var _ss3_forma_decorators;
    var _ss3_forma_initializers = [];
    var _ss3_forma_extraInitializers = [];
    var _ss4_forma_decorators;
    var _ss4_forma_initializers = [];
    var _ss4_forma_extraInitializers = [];
    var _ss5_forma_decorators;
    var _ss5_forma_initializers = [];
    var _ss5_forma_extraInitializers = [];
    var _ss1_zkraceno_decorators;
    var _ss1_zkraceno_initializers = [];
    var _ss1_zkraceno_extraInitializers = [];
    var _ss2_zkraceno_decorators;
    var _ss2_zkraceno_initializers = [];
    var _ss2_zkraceno_extraInitializers = [];
    var _ss3_zkraceno_decorators;
    var _ss3_zkraceno_initializers = [];
    var _ss3_zkraceno_extraInitializers = [];
    var _ss4_zkraceno_decorators;
    var _ss4_zkraceno_initializers = [];
    var _ss4_zkraceno_extraInitializers = [];
    var _ss5_zkraceno_decorators;
    var _ss5_zkraceno_initializers = [];
    var _ss5_zkraceno_extraInitializers = [];
    var _ss1_prijat_decorators;
    var _ss1_prijat_initializers = [];
    var _ss1_prijat_extraInitializers = [];
    var _ss2_prijat_decorators;
    var _ss2_prijat_initializers = [];
    var _ss2_prijat_extraInitializers = [];
    var _ss3_prijat_decorators;
    var _ss3_prijat_initializers = [];
    var _ss3_prijat_extraInitializers = [];
    var _ss4_prijat_decorators;
    var _ss4_prijat_initializers = [];
    var _ss4_prijat_extraInitializers = [];
    var _ss5_prijat_decorators;
    var _ss5_prijat_initializers = [];
    var _ss5_prijat_extraInitializers = [];
    var _ss1_duvod_neprijeti_decorators;
    var _ss1_duvod_neprijeti_initializers = [];
    var _ss1_duvod_neprijeti_extraInitializers = [];
    var _ss2_duvod_neprijeti_decorators;
    var _ss2_duvod_neprijeti_initializers = [];
    var _ss2_duvod_neprijeti_extraInitializers = [];
    var _ss3_duvod_neprijeti_decorators;
    var _ss3_duvod_neprijeti_initializers = [];
    var _ss3_duvod_neprijeti_extraInitializers = [];
    var _ss4_duvod_neprijeti_decorators;
    var _ss4_duvod_neprijeti_initializers = [];
    var _ss4_duvod_neprijeti_extraInitializers = [];
    var _ss5_duvod_neprijeti_decorators;
    var _ss5_duvod_neprijeti_initializers = [];
    var _ss5_duvod_neprijeti_extraInitializers = [];
    var _c_m_procentni_skor_decorators;
    var _c_m_procentni_skor_initializers = [];
    var _c_m_procentni_skor_extraInitializers = [];
    var _c_procentni_skor_decorators;
    var _c_procentni_skor_initializers = [];
    var _c_procentni_skor_extraInitializers = [];
    var _m_procentni_skor_decorators;
    var _m_procentni_skor_initializers = [];
    var _m_procentni_skor_extraInitializers = [];
    var Uchazec = _classThis = /** @class */ (function () {
        function Uchazec_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.rok = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _rok_initializers, void 0));
            this.kolo = (__runInitializers(this, _rok_extraInitializers), __runInitializers(this, _kolo_initializers, void 0));
            this.ss1_redizo = (__runInitializers(this, _kolo_extraInitializers), __runInitializers(this, _ss1_redizo_initializers, void 0));
            this.ss2_redizo = (__runInitializers(this, _ss1_redizo_extraInitializers), __runInitializers(this, _ss2_redizo_initializers, void 0));
            this.ss3_redizo = (__runInitializers(this, _ss2_redizo_extraInitializers), __runInitializers(this, _ss3_redizo_initializers, void 0));
            this.ss4_redizo = (__runInitializers(this, _ss3_redizo_extraInitializers), __runInitializers(this, _ss4_redizo_initializers, void 0));
            this.ss5_redizo = (__runInitializers(this, _ss4_redizo_extraInitializers), __runInitializers(this, _ss5_redizo_initializers, void 0));
            this.ss1_zrizovatel = (__runInitializers(this, _ss5_redizo_extraInitializers), __runInitializers(this, _ss1_zrizovatel_initializers, void 0));
            this.ss2_zrizovatel = (__runInitializers(this, _ss1_zrizovatel_extraInitializers), __runInitializers(this, _ss2_zrizovatel_initializers, void 0));
            this.ss3_zrizovatel = (__runInitializers(this, _ss2_zrizovatel_extraInitializers), __runInitializers(this, _ss3_zrizovatel_initializers, void 0));
            this.ss4_zrizovatel = (__runInitializers(this, _ss3_zrizovatel_extraInitializers), __runInitializers(this, _ss4_zrizovatel_initializers, void 0));
            this.ss5_zrizovatel = (__runInitializers(this, _ss4_zrizovatel_extraInitializers), __runInitializers(this, _ss5_zrizovatel_initializers, void 0));
            this.ss1_kkov = (__runInitializers(this, _ss5_zrizovatel_extraInitializers), __runInitializers(this, _ss1_kkov_initializers, void 0));
            this.ss2_kkov = (__runInitializers(this, _ss1_kkov_extraInitializers), __runInitializers(this, _ss2_kkov_initializers, void 0));
            this.ss3_kkov = (__runInitializers(this, _ss2_kkov_extraInitializers), __runInitializers(this, _ss3_kkov_initializers, void 0));
            this.ss4_kkov = (__runInitializers(this, _ss3_kkov_extraInitializers), __runInitializers(this, _ss4_kkov_initializers, void 0));
            this.ss5_kkov = (__runInitializers(this, _ss4_kkov_extraInitializers), __runInitializers(this, _ss5_kkov_initializers, void 0));
            this.ss1_forma = (__runInitializers(this, _ss5_kkov_extraInitializers), __runInitializers(this, _ss1_forma_initializers, void 0));
            this.ss2_forma = (__runInitializers(this, _ss1_forma_extraInitializers), __runInitializers(this, _ss2_forma_initializers, void 0));
            this.ss3_forma = (__runInitializers(this, _ss2_forma_extraInitializers), __runInitializers(this, _ss3_forma_initializers, void 0));
            this.ss4_forma = (__runInitializers(this, _ss3_forma_extraInitializers), __runInitializers(this, _ss4_forma_initializers, void 0));
            this.ss5_forma = (__runInitializers(this, _ss4_forma_extraInitializers), __runInitializers(this, _ss5_forma_initializers, void 0));
            this.ss1_zkraceno = (__runInitializers(this, _ss5_forma_extraInitializers), __runInitializers(this, _ss1_zkraceno_initializers, void 0));
            this.ss2_zkraceno = (__runInitializers(this, _ss1_zkraceno_extraInitializers), __runInitializers(this, _ss2_zkraceno_initializers, void 0));
            this.ss3_zkraceno = (__runInitializers(this, _ss2_zkraceno_extraInitializers), __runInitializers(this, _ss3_zkraceno_initializers, void 0));
            this.ss4_zkraceno = (__runInitializers(this, _ss3_zkraceno_extraInitializers), __runInitializers(this, _ss4_zkraceno_initializers, void 0));
            this.ss5_zkraceno = (__runInitializers(this, _ss4_zkraceno_extraInitializers), __runInitializers(this, _ss5_zkraceno_initializers, void 0));
            this.ss1_prijat = (__runInitializers(this, _ss5_zkraceno_extraInitializers), __runInitializers(this, _ss1_prijat_initializers, void 0));
            this.ss2_prijat = (__runInitializers(this, _ss1_prijat_extraInitializers), __runInitializers(this, _ss2_prijat_initializers, void 0));
            this.ss3_prijat = (__runInitializers(this, _ss2_prijat_extraInitializers), __runInitializers(this, _ss3_prijat_initializers, void 0));
            this.ss4_prijat = (__runInitializers(this, _ss3_prijat_extraInitializers), __runInitializers(this, _ss4_prijat_initializers, void 0));
            this.ss5_prijat = (__runInitializers(this, _ss4_prijat_extraInitializers), __runInitializers(this, _ss5_prijat_initializers, void 0));
            this.ss1_duvod_neprijeti = (__runInitializers(this, _ss5_prijat_extraInitializers), __runInitializers(this, _ss1_duvod_neprijeti_initializers, void 0));
            this.ss2_duvod_neprijeti = (__runInitializers(this, _ss1_duvod_neprijeti_extraInitializers), __runInitializers(this, _ss2_duvod_neprijeti_initializers, void 0));
            this.ss3_duvod_neprijeti = (__runInitializers(this, _ss2_duvod_neprijeti_extraInitializers), __runInitializers(this, _ss3_duvod_neprijeti_initializers, void 0));
            this.ss4_duvod_neprijeti = (__runInitializers(this, _ss3_duvod_neprijeti_extraInitializers), __runInitializers(this, _ss4_duvod_neprijeti_initializers, void 0));
            this.ss5_duvod_neprijeti = (__runInitializers(this, _ss4_duvod_neprijeti_extraInitializers), __runInitializers(this, _ss5_duvod_neprijeti_initializers, void 0));
            this.c_m_procentni_skor = (__runInitializers(this, _ss5_duvod_neprijeti_extraInitializers), __runInitializers(this, _c_m_procentni_skor_initializers, void 0));
            this.c_procentni_skor = (__runInitializers(this, _c_m_procentni_skor_extraInitializers), __runInitializers(this, _c_procentni_skor_initializers, void 0));
            this.m_procentni_skor = (__runInitializers(this, _c_procentni_skor_extraInitializers), __runInitializers(this, _m_procentni_skor_initializers, void 0));
            __runInitializers(this, _m_procentni_skor_extraInitializers);
        }
        return Uchazec_1;
    }());
    __setFunctionName(_classThis, "Uchazec");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, typeorm_1.PrimaryGeneratedColumn)()];
        _rok_decorators = [(0, typeorm_1.Column)("bigint")];
        _kolo_decorators = [(0, typeorm_1.Column)("bigint")];
        _ss1_redizo_decorators = [(0, typeorm_1.Column)()];
        _ss2_redizo_decorators = [(0, typeorm_1.Column)()];
        _ss3_redizo_decorators = [(0, typeorm_1.Column)()];
        _ss4_redizo_decorators = [(0, typeorm_1.Column)()];
        _ss5_redizo_decorators = [(0, typeorm_1.Column)()];
        _ss1_zrizovatel_decorators = [(0, typeorm_1.Column)()];
        _ss2_zrizovatel_decorators = [(0, typeorm_1.Column)()];
        _ss3_zrizovatel_decorators = [(0, typeorm_1.Column)()];
        _ss4_zrizovatel_decorators = [(0, typeorm_1.Column)()];
        _ss5_zrizovatel_decorators = [(0, typeorm_1.Column)()];
        _ss1_kkov_decorators = [(0, typeorm_1.Column)("text")];
        _ss2_kkov_decorators = [(0, typeorm_1.Column)("text")];
        _ss3_kkov_decorators = [(0, typeorm_1.Column)("text")];
        _ss4_kkov_decorators = [(0, typeorm_1.Column)("text")];
        _ss5_kkov_decorators = [(0, typeorm_1.Column)("text")];
        _ss1_forma_decorators = [(0, typeorm_1.Column)("text")];
        _ss2_forma_decorators = [(0, typeorm_1.Column)("text")];
        _ss3_forma_decorators = [(0, typeorm_1.Column)("text")];
        _ss4_forma_decorators = [(0, typeorm_1.Column)("text")];
        _ss5_forma_decorators = [(0, typeorm_1.Column)("text")];
        _ss1_zkraceno_decorators = [(0, typeorm_1.Column)()];
        _ss2_zkraceno_decorators = [(0, typeorm_1.Column)()];
        _ss3_zkraceno_decorators = [(0, typeorm_1.Column)()];
        _ss4_zkraceno_decorators = [(0, typeorm_1.Column)()];
        _ss5_zkraceno_decorators = [(0, typeorm_1.Column)()];
        _ss1_prijat_decorators = [(0, typeorm_1.Column)()];
        _ss2_prijat_decorators = [(0, typeorm_1.Column)()];
        _ss3_prijat_decorators = [(0, typeorm_1.Column)()];
        _ss4_prijat_decorators = [(0, typeorm_1.Column)()];
        _ss5_prijat_decorators = [(0, typeorm_1.Column)()];
        _ss1_duvod_neprijeti_decorators = [(0, typeorm_1.Column)("text")];
        _ss2_duvod_neprijeti_decorators = [(0, typeorm_1.Column)("text")];
        _ss3_duvod_neprijeti_decorators = [(0, typeorm_1.Column)("text")];
        _ss4_duvod_neprijeti_decorators = [(0, typeorm_1.Column)("text")];
        _ss5_duvod_neprijeti_decorators = [(0, typeorm_1.Column)("text")];
        _c_m_procentni_skor_decorators = [(0, typeorm_1.Column)()];
        _c_procentni_skor_decorators = [(0, typeorm_1.Column)()];
        _m_procentni_skor_decorators = [(0, typeorm_1.Column)()];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _rok_decorators, { kind: "field", name: "rok", static: false, private: false, access: { has: function (obj) { return "rok" in obj; }, get: function (obj) { return obj.rok; }, set: function (obj, value) { obj.rok = value; } }, metadata: _metadata }, _rok_initializers, _rok_extraInitializers);
        __esDecorate(null, null, _kolo_decorators, { kind: "field", name: "kolo", static: false, private: false, access: { has: function (obj) { return "kolo" in obj; }, get: function (obj) { return obj.kolo; }, set: function (obj, value) { obj.kolo = value; } }, metadata: _metadata }, _kolo_initializers, _kolo_extraInitializers);
        __esDecorate(null, null, _ss1_redizo_decorators, { kind: "field", name: "ss1_redizo", static: false, private: false, access: { has: function (obj) { return "ss1_redizo" in obj; }, get: function (obj) { return obj.ss1_redizo; }, set: function (obj, value) { obj.ss1_redizo = value; } }, metadata: _metadata }, _ss1_redizo_initializers, _ss1_redizo_extraInitializers);
        __esDecorate(null, null, _ss2_redizo_decorators, { kind: "field", name: "ss2_redizo", static: false, private: false, access: { has: function (obj) { return "ss2_redizo" in obj; }, get: function (obj) { return obj.ss2_redizo; }, set: function (obj, value) { obj.ss2_redizo = value; } }, metadata: _metadata }, _ss2_redizo_initializers, _ss2_redizo_extraInitializers);
        __esDecorate(null, null, _ss3_redizo_decorators, { kind: "field", name: "ss3_redizo", static: false, private: false, access: { has: function (obj) { return "ss3_redizo" in obj; }, get: function (obj) { return obj.ss3_redizo; }, set: function (obj, value) { obj.ss3_redizo = value; } }, metadata: _metadata }, _ss3_redizo_initializers, _ss3_redizo_extraInitializers);
        __esDecorate(null, null, _ss4_redizo_decorators, { kind: "field", name: "ss4_redizo", static: false, private: false, access: { has: function (obj) { return "ss4_redizo" in obj; }, get: function (obj) { return obj.ss4_redizo; }, set: function (obj, value) { obj.ss4_redizo = value; } }, metadata: _metadata }, _ss4_redizo_initializers, _ss4_redizo_extraInitializers);
        __esDecorate(null, null, _ss5_redizo_decorators, { kind: "field", name: "ss5_redizo", static: false, private: false, access: { has: function (obj) { return "ss5_redizo" in obj; }, get: function (obj) { return obj.ss5_redizo; }, set: function (obj, value) { obj.ss5_redizo = value; } }, metadata: _metadata }, _ss5_redizo_initializers, _ss5_redizo_extraInitializers);
        __esDecorate(null, null, _ss1_zrizovatel_decorators, { kind: "field", name: "ss1_zrizovatel", static: false, private: false, access: { has: function (obj) { return "ss1_zrizovatel" in obj; }, get: function (obj) { return obj.ss1_zrizovatel; }, set: function (obj, value) { obj.ss1_zrizovatel = value; } }, metadata: _metadata }, _ss1_zrizovatel_initializers, _ss1_zrizovatel_extraInitializers);
        __esDecorate(null, null, _ss2_zrizovatel_decorators, { kind: "field", name: "ss2_zrizovatel", static: false, private: false, access: { has: function (obj) { return "ss2_zrizovatel" in obj; }, get: function (obj) { return obj.ss2_zrizovatel; }, set: function (obj, value) { obj.ss2_zrizovatel = value; } }, metadata: _metadata }, _ss2_zrizovatel_initializers, _ss2_zrizovatel_extraInitializers);
        __esDecorate(null, null, _ss3_zrizovatel_decorators, { kind: "field", name: "ss3_zrizovatel", static: false, private: false, access: { has: function (obj) { return "ss3_zrizovatel" in obj; }, get: function (obj) { return obj.ss3_zrizovatel; }, set: function (obj, value) { obj.ss3_zrizovatel = value; } }, metadata: _metadata }, _ss3_zrizovatel_initializers, _ss3_zrizovatel_extraInitializers);
        __esDecorate(null, null, _ss4_zrizovatel_decorators, { kind: "field", name: "ss4_zrizovatel", static: false, private: false, access: { has: function (obj) { return "ss4_zrizovatel" in obj; }, get: function (obj) { return obj.ss4_zrizovatel; }, set: function (obj, value) { obj.ss4_zrizovatel = value; } }, metadata: _metadata }, _ss4_zrizovatel_initializers, _ss4_zrizovatel_extraInitializers);
        __esDecorate(null, null, _ss5_zrizovatel_decorators, { kind: "field", name: "ss5_zrizovatel", static: false, private: false, access: { has: function (obj) { return "ss5_zrizovatel" in obj; }, get: function (obj) { return obj.ss5_zrizovatel; }, set: function (obj, value) { obj.ss5_zrizovatel = value; } }, metadata: _metadata }, _ss5_zrizovatel_initializers, _ss5_zrizovatel_extraInitializers);
        __esDecorate(null, null, _ss1_kkov_decorators, { kind: "field", name: "ss1_kkov", static: false, private: false, access: { has: function (obj) { return "ss1_kkov" in obj; }, get: function (obj) { return obj.ss1_kkov; }, set: function (obj, value) { obj.ss1_kkov = value; } }, metadata: _metadata }, _ss1_kkov_initializers, _ss1_kkov_extraInitializers);
        __esDecorate(null, null, _ss2_kkov_decorators, { kind: "field", name: "ss2_kkov", static: false, private: false, access: { has: function (obj) { return "ss2_kkov" in obj; }, get: function (obj) { return obj.ss2_kkov; }, set: function (obj, value) { obj.ss2_kkov = value; } }, metadata: _metadata }, _ss2_kkov_initializers, _ss2_kkov_extraInitializers);
        __esDecorate(null, null, _ss3_kkov_decorators, { kind: "field", name: "ss3_kkov", static: false, private: false, access: { has: function (obj) { return "ss3_kkov" in obj; }, get: function (obj) { return obj.ss3_kkov; }, set: function (obj, value) { obj.ss3_kkov = value; } }, metadata: _metadata }, _ss3_kkov_initializers, _ss3_kkov_extraInitializers);
        __esDecorate(null, null, _ss4_kkov_decorators, { kind: "field", name: "ss4_kkov", static: false, private: false, access: { has: function (obj) { return "ss4_kkov" in obj; }, get: function (obj) { return obj.ss4_kkov; }, set: function (obj, value) { obj.ss4_kkov = value; } }, metadata: _metadata }, _ss4_kkov_initializers, _ss4_kkov_extraInitializers);
        __esDecorate(null, null, _ss5_kkov_decorators, { kind: "field", name: "ss5_kkov", static: false, private: false, access: { has: function (obj) { return "ss5_kkov" in obj; }, get: function (obj) { return obj.ss5_kkov; }, set: function (obj, value) { obj.ss5_kkov = value; } }, metadata: _metadata }, _ss5_kkov_initializers, _ss5_kkov_extraInitializers);
        __esDecorate(null, null, _ss1_forma_decorators, { kind: "field", name: "ss1_forma", static: false, private: false, access: { has: function (obj) { return "ss1_forma" in obj; }, get: function (obj) { return obj.ss1_forma; }, set: function (obj, value) { obj.ss1_forma = value; } }, metadata: _metadata }, _ss1_forma_initializers, _ss1_forma_extraInitializers);
        __esDecorate(null, null, _ss2_forma_decorators, { kind: "field", name: "ss2_forma", static: false, private: false, access: { has: function (obj) { return "ss2_forma" in obj; }, get: function (obj) { return obj.ss2_forma; }, set: function (obj, value) { obj.ss2_forma = value; } }, metadata: _metadata }, _ss2_forma_initializers, _ss2_forma_extraInitializers);
        __esDecorate(null, null, _ss3_forma_decorators, { kind: "field", name: "ss3_forma", static: false, private: false, access: { has: function (obj) { return "ss3_forma" in obj; }, get: function (obj) { return obj.ss3_forma; }, set: function (obj, value) { obj.ss3_forma = value; } }, metadata: _metadata }, _ss3_forma_initializers, _ss3_forma_extraInitializers);
        __esDecorate(null, null, _ss4_forma_decorators, { kind: "field", name: "ss4_forma", static: false, private: false, access: { has: function (obj) { return "ss4_forma" in obj; }, get: function (obj) { return obj.ss4_forma; }, set: function (obj, value) { obj.ss4_forma = value; } }, metadata: _metadata }, _ss4_forma_initializers, _ss4_forma_extraInitializers);
        __esDecorate(null, null, _ss5_forma_decorators, { kind: "field", name: "ss5_forma", static: false, private: false, access: { has: function (obj) { return "ss5_forma" in obj; }, get: function (obj) { return obj.ss5_forma; }, set: function (obj, value) { obj.ss5_forma = value; } }, metadata: _metadata }, _ss5_forma_initializers, _ss5_forma_extraInitializers);
        __esDecorate(null, null, _ss1_zkraceno_decorators, { kind: "field", name: "ss1_zkraceno", static: false, private: false, access: { has: function (obj) { return "ss1_zkraceno" in obj; }, get: function (obj) { return obj.ss1_zkraceno; }, set: function (obj, value) { obj.ss1_zkraceno = value; } }, metadata: _metadata }, _ss1_zkraceno_initializers, _ss1_zkraceno_extraInitializers);
        __esDecorate(null, null, _ss2_zkraceno_decorators, { kind: "field", name: "ss2_zkraceno", static: false, private: false, access: { has: function (obj) { return "ss2_zkraceno" in obj; }, get: function (obj) { return obj.ss2_zkraceno; }, set: function (obj, value) { obj.ss2_zkraceno = value; } }, metadata: _metadata }, _ss2_zkraceno_initializers, _ss2_zkraceno_extraInitializers);
        __esDecorate(null, null, _ss3_zkraceno_decorators, { kind: "field", name: "ss3_zkraceno", static: false, private: false, access: { has: function (obj) { return "ss3_zkraceno" in obj; }, get: function (obj) { return obj.ss3_zkraceno; }, set: function (obj, value) { obj.ss3_zkraceno = value; } }, metadata: _metadata }, _ss3_zkraceno_initializers, _ss3_zkraceno_extraInitializers);
        __esDecorate(null, null, _ss4_zkraceno_decorators, { kind: "field", name: "ss4_zkraceno", static: false, private: false, access: { has: function (obj) { return "ss4_zkraceno" in obj; }, get: function (obj) { return obj.ss4_zkraceno; }, set: function (obj, value) { obj.ss4_zkraceno = value; } }, metadata: _metadata }, _ss4_zkraceno_initializers, _ss4_zkraceno_extraInitializers);
        __esDecorate(null, null, _ss5_zkraceno_decorators, { kind: "field", name: "ss5_zkraceno", static: false, private: false, access: { has: function (obj) { return "ss5_zkraceno" in obj; }, get: function (obj) { return obj.ss5_zkraceno; }, set: function (obj, value) { obj.ss5_zkraceno = value; } }, metadata: _metadata }, _ss5_zkraceno_initializers, _ss5_zkraceno_extraInitializers);
        __esDecorate(null, null, _ss1_prijat_decorators, { kind: "field", name: "ss1_prijat", static: false, private: false, access: { has: function (obj) { return "ss1_prijat" in obj; }, get: function (obj) { return obj.ss1_prijat; }, set: function (obj, value) { obj.ss1_prijat = value; } }, metadata: _metadata }, _ss1_prijat_initializers, _ss1_prijat_extraInitializers);
        __esDecorate(null, null, _ss2_prijat_decorators, { kind: "field", name: "ss2_prijat", static: false, private: false, access: { has: function (obj) { return "ss2_prijat" in obj; }, get: function (obj) { return obj.ss2_prijat; }, set: function (obj, value) { obj.ss2_prijat = value; } }, metadata: _metadata }, _ss2_prijat_initializers, _ss2_prijat_extraInitializers);
        __esDecorate(null, null, _ss3_prijat_decorators, { kind: "field", name: "ss3_prijat", static: false, private: false, access: { has: function (obj) { return "ss3_prijat" in obj; }, get: function (obj) { return obj.ss3_prijat; }, set: function (obj, value) { obj.ss3_prijat = value; } }, metadata: _metadata }, _ss3_prijat_initializers, _ss3_prijat_extraInitializers);
        __esDecorate(null, null, _ss4_prijat_decorators, { kind: "field", name: "ss4_prijat", static: false, private: false, access: { has: function (obj) { return "ss4_prijat" in obj; }, get: function (obj) { return obj.ss4_prijat; }, set: function (obj, value) { obj.ss4_prijat = value; } }, metadata: _metadata }, _ss4_prijat_initializers, _ss4_prijat_extraInitializers);
        __esDecorate(null, null, _ss5_prijat_decorators, { kind: "field", name: "ss5_prijat", static: false, private: false, access: { has: function (obj) { return "ss5_prijat" in obj; }, get: function (obj) { return obj.ss5_prijat; }, set: function (obj, value) { obj.ss5_prijat = value; } }, metadata: _metadata }, _ss5_prijat_initializers, _ss5_prijat_extraInitializers);
        __esDecorate(null, null, _ss1_duvod_neprijeti_decorators, { kind: "field", name: "ss1_duvod_neprijeti", static: false, private: false, access: { has: function (obj) { return "ss1_duvod_neprijeti" in obj; }, get: function (obj) { return obj.ss1_duvod_neprijeti; }, set: function (obj, value) { obj.ss1_duvod_neprijeti = value; } }, metadata: _metadata }, _ss1_duvod_neprijeti_initializers, _ss1_duvod_neprijeti_extraInitializers);
        __esDecorate(null, null, _ss2_duvod_neprijeti_decorators, { kind: "field", name: "ss2_duvod_neprijeti", static: false, private: false, access: { has: function (obj) { return "ss2_duvod_neprijeti" in obj; }, get: function (obj) { return obj.ss2_duvod_neprijeti; }, set: function (obj, value) { obj.ss2_duvod_neprijeti = value; } }, metadata: _metadata }, _ss2_duvod_neprijeti_initializers, _ss2_duvod_neprijeti_extraInitializers);
        __esDecorate(null, null, _ss3_duvod_neprijeti_decorators, { kind: "field", name: "ss3_duvod_neprijeti", static: false, private: false, access: { has: function (obj) { return "ss3_duvod_neprijeti" in obj; }, get: function (obj) { return obj.ss3_duvod_neprijeti; }, set: function (obj, value) { obj.ss3_duvod_neprijeti = value; } }, metadata: _metadata }, _ss3_duvod_neprijeti_initializers, _ss3_duvod_neprijeti_extraInitializers);
        __esDecorate(null, null, _ss4_duvod_neprijeti_decorators, { kind: "field", name: "ss4_duvod_neprijeti", static: false, private: false, access: { has: function (obj) { return "ss4_duvod_neprijeti" in obj; }, get: function (obj) { return obj.ss4_duvod_neprijeti; }, set: function (obj, value) { obj.ss4_duvod_neprijeti = value; } }, metadata: _metadata }, _ss4_duvod_neprijeti_initializers, _ss4_duvod_neprijeti_extraInitializers);
        __esDecorate(null, null, _ss5_duvod_neprijeti_decorators, { kind: "field", name: "ss5_duvod_neprijeti", static: false, private: false, access: { has: function (obj) { return "ss5_duvod_neprijeti" in obj; }, get: function (obj) { return obj.ss5_duvod_neprijeti; }, set: function (obj, value) { obj.ss5_duvod_neprijeti = value; } }, metadata: _metadata }, _ss5_duvod_neprijeti_initializers, _ss5_duvod_neprijeti_extraInitializers);
        __esDecorate(null, null, _c_m_procentni_skor_decorators, { kind: "field", name: "c_m_procentni_skor", static: false, private: false, access: { has: function (obj) { return "c_m_procentni_skor" in obj; }, get: function (obj) { return obj.c_m_procentni_skor; }, set: function (obj, value) { obj.c_m_procentni_skor = value; } }, metadata: _metadata }, _c_m_procentni_skor_initializers, _c_m_procentni_skor_extraInitializers);
        __esDecorate(null, null, _c_procentni_skor_decorators, { kind: "field", name: "c_procentni_skor", static: false, private: false, access: { has: function (obj) { return "c_procentni_skor" in obj; }, get: function (obj) { return obj.c_procentni_skor; }, set: function (obj, value) { obj.c_procentni_skor = value; } }, metadata: _metadata }, _c_procentni_skor_initializers, _c_procentni_skor_extraInitializers);
        __esDecorate(null, null, _m_procentni_skor_decorators, { kind: "field", name: "m_procentni_skor", static: false, private: false, access: { has: function (obj) { return "m_procentni_skor" in obj; }, get: function (obj) { return obj.m_procentni_skor; }, set: function (obj, value) { obj.m_procentni_skor = value; } }, metadata: _metadata }, _m_procentni_skor_initializers, _m_procentni_skor_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        Uchazec = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return Uchazec = _classThis;
}();
exports.Uchazec = Uchazec;
